#
###################################
# Site wide configuration
####################################
#
title: Leonids
email:
description: A simple and awesome blog theme powered by jekyll.
url: https://bilardi.github.io/leonids # the base hostname & protocol for your site
repository-forked: http://github.com/bilardi/leonids/ # in the footer
favicon: # links of your favicon
  - favicon.ico
  - favicon.png
#  - external link
keywords: ["blog", "jekyll"]
meta:
  twitter-image: leonids-logo.png # or external link
  og-image: leonids-logo.png # or external link
home:
  hide-on-sidebar: false
#  icon: fa-leaf
#  icon: fa-home
readme:
  hide-on-sidebar: true
  title: about
  url: about.html
navigation:
  hide-on-sidebar: false
  hide-on-post: false
  left:
#    icon: fa-angle-left
    icon: fa-arrow-left
    color: danger
  home:
#    icon: fa-leaf
    icon: fa-home
    color: warning
  right:
#    icon: fa-angle-right
    icon: fa-arrow-right
    color: success
collection:
  categories:
    class: cat
    hide-on-post: false
    btn-on-post: false
    hide-on-archive: true
    btn-on-archive: true
    hide-on-tags: true
    btn-on-tags: true
  tags:
    class: tag
    hide-on-post: false
    btn-on-post: false
    hide-on-archive: true
    btn-on-archive: true
    hide-on-categories: true
    btn-on-categories: true
resume:
  hide-routines: false
  hide-projects: false
  hide-skills: false

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-redirect-from
#  - jekyll-readme-index
#  - jekyll-feed

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Leonids
  author:
    name: #your name
    link: #your homepage
  avatar: leonids-logo.png # or external link
  job: "A jekyll theme"
  bio: "A simple and awesome blog theme powered by jekyll."
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
  wikipedia: #username
  custom:
    - url: http://github.com/bilardi/leonids/
      icon: fa-code
    - url: http://github.com/renyuanz/leonids/
      icon: fa-code-fork

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

style:
  text:
    color: rgba(0, 0, 0, 0.87)
  author:
    color: "#F36170"
  background:
    color: "#f5f5f5"
    image: #http://domain.name/path/background.jpg
    size: cover
  navigation-background:
    color: "#f6f6f6"
  color:
    white: "#fff"
    primary: "#42b983"
    secondary: "#8d7edc"
    success: "#65e892"
    danger: "#f83e4b"
    warning: "#F5A623"
    info: "#09ABF6"
